name: Request HTTP
on:
  push:
    branches:
      - main

jobs:
  request-http:
    runs-on: ubuntu-latest

    steps:
    - name: Make HTTP Request
      uses: actions/http-request@v2
      with:
        url: 'https://geralsite.onrender.com/teste_server'  # Substitua pela URL desejada
